# Generated by Django 4.2.5 on 2023-09-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('quant', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.FloatField(default=0.0)),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restauranteapp.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.FloatField(default=0.0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restauranteapp.menuitens')),
            ],
        ),
    ]
